  
version: '3'
services:
  client:
    build:
      context: docker
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      - HOST=0.0.0.0
    ports:
      - "90:3000"
    tty: true